-- Task 2.3: 初期アイテムマスタ。仕様の7カテゴリ×5レアリティ。抽選対象は enabled_for_drop=1。
-- 本番デプロイ時は必ずマイグレーションを適用すること（未投入のままデプロイしない）。
PRAGMA foreign_keys = ON;
--> statement-breakpoint
INSERT INTO `items` (`id`, `category`, `rarity`, `name`, `description`, `enabled_for_drop`, `created_at`, `updated_at`) VALUES
('drink-common-01', 'drink', 'common', 'エナジーウォーター', '基本的な回復飲料。薄い青色', 1, NULL, NULL),
('drink-rare-01', 'drink', 'rare', 'ネオンソーダ', '青く光るソーダ。泡がネオンに光る', 1, NULL, NULL),
('drink-sr-01', 'drink', 'super-rare', 'サイバーカクテル', '紫に輝くカクテル。グラスにデジタル紋様', 1, NULL, NULL),
('drink-ur-01', 'drink', 'ultra-rare', 'ゴールデンエリクサー', '金色に輝く特別な一杯。瓶が浮遊している', 1, NULL, NULL),
('drink-legend-01', 'drink', 'legend', 'レインボーアムリタ', '虹色に変化する伝説の霊薬。ホログラフィック', 1, NULL, NULL),
('chip-common-01', 'chip', 'common', 'メモリーチップ', '基本的なデータチップ。灰色', 1, NULL, NULL),
('chip-rare-01', 'chip', 'rare', '暗号キーチップ', '青い回路が浮き出たチップ', 1, NULL, NULL),
('chip-sr-01', 'chip', 'super-rare', 'ニューラルプロセッサ', '紫の光を放つ高性能チップ', 1, NULL, NULL),
('chip-ur-01', 'chip', 'ultra-rare', '量子コアチップ', '金色の量子回路が浮かぶチップ', 1, NULL, NULL),
('chip-legend-01', 'chip', 'legend', 'ゼロデイチップ', '虹色のデータが渦巻く伝説級チップ', 1, NULL, NULL),
('badge-common-01', 'badge', 'common', 'ブロンズバッジ', 'シンプルな銅の紋章', 1, NULL, NULL),
('badge-rare-01', 'badge', 'rare', 'シルバークレスト', '青い光を帯びた銀の紋章', 1, NULL, NULL),
('badge-sr-01', 'badge', 'super-rare', 'ネオンシールド', '紫に発光するデジタル紋章', 1, NULL, NULL),
('badge-ur-01', 'badge', 'ultra-rare', 'ゴールドエンブレム', '金色に輝くエリートの証', 1, NULL, NULL),
('badge-legend-01', 'badge', 'legend', 'ホログラムスター', '虹色に変化する最高位の星章', 1, NULL, NULL),
('tool-common-01', 'tool', 'common', 'ホロペン', '基本的なデジタルペン。メモ用', 1, NULL, NULL),
('tool-rare-01', 'tool', 'rare', 'スキャナードローン', '青い光の小型偵察ドローン', 1, NULL, NULL),
('tool-sr-01', 'tool', 'super-rare', 'ハックグローブ', '紫のネオンが走るハッキング用手袋', 1, NULL, NULL),
('tool-ur-01', 'tool', 'ultra-rare', 'ニューラルリンク', '金色のインターフェースデバイス', 1, NULL, NULL),
('tool-legend-01', 'tool', 'legend', 'ファントムバイザー', '虹色に輝く万能ARバイザー', 1, NULL, NULL),
('artifact-common-01', 'artifact', 'common', '古びた回路基板', '過去の時代の電子基板', 1, NULL, NULL),
('artifact-rare-01', 'artifact', 'rare', 'データクリスタル', '青く透き通る結晶状のデータ媒体', 1, NULL, NULL),
('artifact-sr-01', 'artifact', 'super-rare', 'ホログラム地図', '紫に浮かぶ都市の3Dホログラム', 1, NULL, NULL),
('artifact-ur-01', 'artifact', 'ultra-rare', '黄金のコード断片', '金色に輝く失われたプログラムコード', 1, NULL, NULL),
('artifact-legend-01', 'artifact', 'legend', 'AIコア「プロメテウス」', '虹色に脈動する古代のAI中枢', 1, NULL, NULL),
('android-common-01', 'android', 'common', '雑用アンドロイド', 'シンプルな雑用ロボット。灰色のボディ', 1, NULL, NULL),
('android-rare-01', 'android', 'rare', 'アシストユニット', '青い光を帯びた補助用アンドロイド', 1, NULL, NULL),
('android-sr-01', 'android', 'super-rare', 'ネオンドロイド', '紫のネオンが走る高機能アンドロイド', 1, NULL, NULL),
('android-ur-01', 'android', 'ultra-rare', 'ゴールドアンドロイド', '金色に輝くプレミアムアンドロイド', 1, NULL, NULL),
('android-legend-01', 'android', 'legend', '覚醒アンドロイド', '虹色に脈動する伝説の自我覚醒体', 1, NULL, NULL),
('mythical-common-01', 'mythical', 'common', '小精霊', 'シンプルな精霊。くすんだ色の小さな存在', 1, NULL, NULL),
('mythical-rare-01', 'mythical', 'rare', '水竜の子', '青い光を帯びた小さな水竜', 1, NULL, NULL),
('mythical-sr-01', 'mythical', 'super-rare', '紫電の雷獣', '紫のネオンが走る雷獣', 1, NULL, NULL),
('mythical-ur-01', 'mythical', 'ultra-rare', '黄金の不死鳥', '金色に輝く不死鳥', 1, NULL, NULL),
('mythical-legend-01', 'mythical', 'legend', '虹の守護竜', '虹色に脈動する伝説の守護竜', 1, NULL, NULL);
